with src as (
    select 
        *   
         ,'{{source('cmlsyspro','InvMaster+')}}' as etl_src_table_name
         ,'CMLSYSPRO'                                as source_system
    from landing_db.cmlsyspro."InvMaster+"
)
,deduped as (
    select
        *,
        row_number() over (partition by stockcode order by _rivery_last_update desc) row_nbr
    from src
)
select
	stockcode,
	pctscrap,
	timestamp,
	pctoverissue,
	weighorcountitem,
	lotexpirydatereqd,
	bomvalidatedforgol,
	risklevel,
	avatax,
	traceableitem,
	revreccat,
	materials,
	resin,
	status,
	availstatuschange,
	market,
	validationguide,
	a510kapproved,
	a510kclass,
	eucemark,
	eucemarkclass,
	extractablesavaila,
	dehpfree,
	adcf,
	bsetsestatement,
	filmplatform,
	biocompatibilityte,
	qualityhold,
	applicationstudies,
	alternativeproduct,
	healthcanadaapprov,
	sterile,
	sterilizationmetho,
	sterilizationlimit,
	brand,
	componentfamily,
	singlesource,
	singlemfgsite,
	shelflifestatement,
	stocktype,
	gammastability,
	mocstatement,
	biocompatibilityst,
	cas,
	uspfclassiv,
	bpafree,
	nitrosaminefree,
	melaminefree,
	latexfree,
	reachcompliant,
	medicalapplication,
	msds,
	dmf,
	minworkingtemp,
	maxworking,
	peristalticpump,
	weldability,
	incompatiblemateri,
	partstatus,
	devprogram,
	productfamily,
	subcat,
	salescategory,
	contractmanustock,
	coreprodtype,
	application,
	coretechnology,
	customer1,
	customer2,
	_rivery_river_id,
	_rivery_run_id,
	_rivery_last_update,
    etl_src_table_name,
 	source_system
from deduped
where row_nbr = 1
